services:
  jekyll-site:
    platform: linux/arm64
    image: jekyll-site
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/local/bundle
    ports: [ 4000:4000 ]
    user: 1000:1000
    environment: [ JEKYLL_ENV=docker ]
    command: bundle exec jekyll serve -H 0.0.0.0 -P 4000 --force_polling --config _config.yml,_config_docker.yml
